import { RawPuzzleJSON } from '../../../application/factories/PuzzleFactory';

export const PUZZLES_DATA: RawPuzzleJSON[] = [
  {
    id: 'case-014-hiking-trip',
    caseNumber: 14,
    title: 'The Hiking Trip',
    difficulty: 'HARD',
    briefing: '¡Vincenza fue asesinada! El asesino estuvo a solas con ella en la misma zona del parque. Cada fila y columna contiene a lo sumo 1 persona.',
    victimId: 'Vincenza',
    murdererId: 'Danika',
    dimensions: { rows: 6, cols: 6 },
    suspects: [
      { id: 'Aubrey', name: 'Aubrey', initial: 'A', color: '#B8D0EB', attributes: { hasHat: true }, clueSummary: 'Windy Trail • Lleva gorra', avatarIcon: '🧢' },
      { id: 'Brianna', name: 'Brianna', initial: 'B', color: '#FCD5CE', attributes: {}, clueSummary: '2 filas al norte de Finlay', avatarIcon: '👱🏻‍♀️' },
      { id: 'Clark', name: 'Clark', initial: 'C', color: '#D8E2DC', attributes: { hasGlasses: true }, clueSummary: 'Rocky Trail • Lleva gafas', avatarIcon: '🕶️' },
      { id: 'Danika', name: 'Danika', initial: 'D', color: '#DDBEA9', attributes: {}, clueSummary: 'Sola en Pine Forest (Asesina)', avatarIcon: '👵🏻' },
      { id: 'Elias', name: 'Elias', initial: 'E', color: '#E2ECE9', attributes: {}, clueSummary: "En Ranger's Hut", avatarIcon: '🧔🏼' },
      { id: 'Finlay', name: 'Finlay', initial: 'F', color: '#FFE5D9', attributes: {}, clueSummary: 'Oso en columna a 4 norte', avatarIcon: '🧔🏻‍♂️' },
      { id: 'Gavin', name: 'Gavin', initial: 'G', color: '#FFD6A5', attributes: {}, clueSummary: 'Al lado de una roca', avatarIcon: '👱🏻‍♂️' },
      { id: 'Hank', name: 'Hank', initial: 'H', color: '#EBCFB2', attributes: {}, clueSummary: 'Fila inferior del parque', avatarIcon: '👴🏻' },
      { id: 'Iris', name: 'Iris', initial: 'I', color: '#E0AAFF', attributes: {}, clueSummary: 'Sentada en la silla [5,1]', avatarIcon: '🪑' },
      { id: 'Joe', name: 'Joe', initial: 'J', color: '#B7B7A4', attributes: {}, clueSummary: 'Al lado de un oso', avatarIcon: '🐾' },
      { id: 'Kobe', name: 'Kobe', initial: 'K', color: '#FFDFBA', attributes: {}, clueSummary: 'En sector The Grove', avatarIcon: '🌿' },
      { id: 'Vincenza', name: 'Vincenza', initial: 'V', color: '#F8C8D2', attributes: { isVictim: true }, clueSummary: 'LA VÍCTIMA (Asesinada a solas)', avatarIcon: '💀' },
    ],
    grid: [
      // Fila 0
      { row: 0, col: 0, zoneName: 'SUMMIT', isOccupable: true },
      { row: 0, col: 1, zoneName: 'SUMMIT', obstacleType: 'BOULDER', isOccupable: false, fixtureIcon: '🪨' },
      { row: 0, col: 2, zoneName: 'SUMMIT', isOccupable: true },
      { row: 0, col: 3, zoneName: "RANGER'S HUT", isOccupable: true },
      { row: 0, col: 4, zoneName: "RANGER'S HUT", obstacleType: 'BEAR', isOccupable: false, fixtureIcon: '🐻' },
      { row: 0, col: 5, zoneName: "RANGER'S HUT", isOccupable: true },

      // Fila 1
      { row: 1, col: 0, zoneName: 'PINE FOREST', obstacleType: 'TREE', isOccupable: false, fixtureIcon: '🌲' },
      { row: 1, col: 1, zoneName: 'PINE FOREST', isOccupable: true },
      { row: 1, col: 2, zoneName: 'PINE FOREST', obstacleType: 'BOULDER', isOccupable: false, fixtureIcon: '🪨' },
      { row: 1, col: 3, zoneName: 'PINE FOREST', obstacleType: 'TABLE', isOccupable: false, fixtureIcon: '🪵' },
      { row: 1, col: 4, zoneName: 'PINE FOREST', obstacleType: 'TREE', isOccupable: false, fixtureIcon: '🌲' },
      { row: 1, col: 5, zoneName: "RANGER'S HUT", isOccupable: true },

      // Fila 2
      { row: 2, col: 0, zoneName: 'PINE FOREST', obstacleType: 'TREE', isOccupable: false, fixtureIcon: '🌲' },
      { row: 2, col: 1, zoneName: 'PINE FOREST', isOccupable: true },
      { row: 2, col: 2, zoneName: 'PINE FOREST', obstacleType: 'SHRUB', isOccupable: false, fixtureIcon: '🌿' },
      { row: 2, col: 3, zoneName: 'PINE FOREST', isOccupable: true },
      { row: 2, col: 4, zoneName: 'PINE FOREST', obstacleType: 'TREE', isOccupable: false, fixtureIcon: '🌲' },
      { row: 2, col: 5, zoneName: 'GROVE', isOccupable: true },

      // Fila 3
      { row: 3, col: 0, zoneName: 'WINDY TRAIL', obstacleType: 'TREE', isOccupable: false, fixtureIcon: '🌲' },
      { row: 3, col: 1, zoneName: 'WINDY TRAIL', isOccupable: true },
      { row: 3, col: 2, zoneName: 'BEAR WOODS', isOccupable: true },
      { row: 3, col: 3, zoneName: 'BEAR WOODS', obstacleType: 'SHRUB', isOccupable: false, fixtureIcon: '🌿' },
      { row: 3, col: 4, zoneName: 'GROVE', isOccupable: true },
      { row: 3, col: 5, zoneName: 'GROVE', obstacleType: 'TREE', isOccupable: false, fixtureIcon: '🌲' },

      // Fila 4
      { row: 4, col: 0, zoneName: 'WINDY TRAIL', obstacleType: 'TREE', isOccupable: false, fixtureIcon: '🌲' },
      { row: 4, col: 1, zoneName: 'WINDY TRAIL', isOccupable: true },
      { row: 4, col: 2, zoneName: 'BEAR WOODS', obstacleType: 'BEAR', isOccupable: false, fixtureIcon: '🐻' },
      { row: 4, col: 3, zoneName: 'BEAR WOODS', isOccupable: true },
      { row: 4, col: 4, zoneName: 'GROVE', obstacleType: 'TREE', isOccupable: false, fixtureIcon: '🌲' },
      { row: 4, col: 5, zoneName: 'LAKE', isOccupable: true },

      // Fila 5
      { row: 5, col: 0, zoneName: 'WINDY TRAIL', isOccupable: true },
      { row: 5, col: 1, zoneName: 'WINDY TRAIL', isOccupable: true, fixtureIcon: '🪑' }, // Iris's Chair
      { row: 5, col: 2, zoneName: 'BEAR WOODS', obstacleType: 'BENCH', isOccupable: false, fixtureIcon: '🛋️' },
      { row: 5, col: 3, zoneName: 'ROCKY TRAIL', isOccupable: true },
      { row: 5, col: 4, zoneName: 'ROCKY TRAIL', isOccupable: true },
      { row: 5, col: 5, zoneName: 'LAKE', obstacleType: 'LAKE', isOccupable: false, fixtureIcon: '💧' },
    ],
    clues: [
      {
        id: 'clue-iris-chair',
        text: 'Iris estaba sentada exactamente en la silla de descanso de Windy Trail [Fila 5, Columna 1].',
        type: 'DIRECT',
        context: { suspectId: 'Iris', exactRow: 5, exactCol: 1, expectedZone: 'WINDY TRAIL' },
        suspectId: 'Iris',
        icon: '🪑',
        tag: 'Silla',
      },
      {
        id: 'clue-danika-pine',
        text: 'Danika estaba completamente sola en el sector Pine Forest.',
        type: 'EXCLUSION',
        context: { suspectId: 'Danika', mustBeAloneInZone: true, zoneName: 'PINE FOREST' },
        suspectId: 'Danika',
        icon: '🌲',
        tag: 'Clave Asesina',
      },
      {
        id: 'clue-aubrey-windy',
        text: 'Aubrey estaba en Windy Trail.',
        type: 'DIRECT',
        context: { suspectId: 'Aubrey', expectedZone: 'WINDY TRAIL' },
        suspectId: 'Aubrey',
        icon: '🧢',
        tag: 'Windy Trail',
      },
      {
        id: 'clue-clark-rocky',
        text: 'Clark estaba en Rocky Trail.',
        type: 'DIRECT',
        context: { suspectId: 'Clark', expectedZone: 'ROCKY TRAIL' },
        suspectId: 'Clark',
        icon: '🕶️',
        tag: 'Rocky Trail',
      },
      {
        id: 'clue-elias-ranger',
        text: "Elias estaba dentro del recinto Ranger's Hut.",
        type: 'DIRECT',
        context: { suspectId: 'Elias', expectedZone: "RANGER'S HUT" },
        suspectId: 'Elias',
        icon: '🛖',
        tag: "Ranger's Hut",
      },
      {
        id: 'clue-brianna-finlay',
        text: 'Brianna estaba exactamente 2 filas al norte de Finlay.',
        type: 'CONDITIONAL',
        context: { primarySuspectId: 'Brianna', referenceSuspectId: 'Finlay', relativeRows: -2 },
        suspectId: 'Brianna',
        icon: '📐',
        tag: 'Distancia',
      },
      {
        id: 'clue-finlay-bear',
        text: 'Había un oso en la columna de Finlay, exactamente 4 filas al norte de él.',
        type: 'CONDITIONAL',
        context: { primarySuspectId: 'Finlay', referenceObstacle: 'BEAR', sameColumn: true, relativeRows: -4 },
        suspectId: 'Finlay',
        icon: '🐻',
        tag: 'Columna Oso',
      },
      {
        id: 'clue-joe-bear',
        text: 'Joe estaba al lado («beside»: contiguo en la misma zona) de un oso.',
        type: 'EXCLUSION',
        context: { suspectId: 'Joe', besideObstacleType: 'BEAR' },
        suspectId: 'Joe',
        icon: '🐾',
        tag: 'Beside Oso',
      },
    ],
  },
  {
    id: 'case-015-fishes',
    caseNumber: 15,
    title: 'Sleeping with the Fishes',
    difficulty: 'HARD',
    briefing: 'Tragedia en la dársena 4. Vincenza fue asesinada en la zona portuaria. El culpable estuvo a solas con ella.',
    victimId: 'Vincenza',
    murdererId: 'Antonio',
    dimensions: { rows: 5, cols: 5 },
    suspects: [
      { id: 'Antonio', name: 'Antonio', initial: 'A', color: '#E0A96D', attributes: {}, clueSummary: 'Estaba en un bote (Asesino)', avatarIcon: '🚤' },
      { id: 'Barry', name: 'Barry', initial: 'B', color: '#8E9AAF', attributes: {}, clueSummary: 'Había una mujer al lado de una caja en su área', avatarIcon: '📦' },
      { id: 'Claire', name: 'Claire', initial: 'C', color: '#F4A261', attributes: {}, clueSummary: 'En un bote al este de Antonio', avatarIcon: '🧭' },
      { id: 'Delilah', name: 'Delilah', initial: 'D', color: '#DDBEA9', attributes: {}, clueSummary: 'En el Fish Market', avatarIcon: '🐟' },
      { id: 'Vincenza', name: 'Vincenza', initial: 'V', color: '#F8C8D2', attributes: { isVictim: true }, clueSummary: 'LA VÍCTIMA', avatarIcon: '💀' },
    ],
    grid: [
      { row: 0, col: 0, zoneName: 'SEA', obstacleType: 'SHELF', isOccupable: false, fixtureIcon: '🧱' },
      { row: 0, col: 1, zoneName: 'SEA', isOccupable: true, fixtureIcon: '🚤' },
      { row: 0, col: 2, zoneName: 'SEA', isOccupable: false, obstacleType: 'BOULDER', fixtureIcon: '🪨' },
      { row: 0, col: 3, zoneName: 'DOCK B', isOccupable: true },
      { row: 0, col: 4, zoneName: 'DOCK B', obstacleType: 'CRATE', isOccupable: false, fixtureIcon: '📦' },

      { row: 1, col: 0, zoneName: 'BOATHOUSE', obstacleType: 'CRATE', isOccupable: false, fixtureIcon: '📦' },
      { row: 1, col: 1, zoneName: 'BOATHOUSE', isOccupable: true, fixtureIcon: '🚤' },
      { row: 1, col: 2, zoneName: 'DOCK A', isOccupable: true },
      { row: 1, col: 3, zoneName: 'DOCK B', isOccupable: true },
      { row: 1, col: 4, zoneName: 'DOCK B', isOccupable: false, obstacleType: 'SHELF', fixtureIcon: '🧱' },

      { row: 2, col: 0, zoneName: 'BOARDWALK', isOccupable: true, fixtureIcon: '🪑' },
      { row: 2, col: 1, zoneName: 'BOARDWALK', isOccupable: true, fixtureIcon: '🪑' },
      { row: 2, col: 2, zoneName: 'BOARDWALK', isOccupable: true },
      { row: 2, col: 3, zoneName: 'WAREHOUSE', obstacleType: 'CRATE', isOccupable: false, fixtureIcon: '📦' },
      { row: 2, col: 4, zoneName: 'WAREHOUSE', isOccupable: true, fixtureIcon: '🪑' },

      { row: 3, col: 0, zoneName: 'FISH MARKET', obstacleType: 'CRATE', isOccupable: false, fixtureIcon: '📦' },
      { row: 3, col: 1, zoneName: 'FISH MARKET', isOccupable: true },
      { row: 3, col: 2, zoneName: 'BOARDWALK', isOccupable: true },
      { row: 3, col: 3, zoneName: 'WAREHOUSE', isOccupable: true },
      { row: 3, col: 4, zoneName: 'WAREHOUSE', obstacleType: 'SHELF', isOccupable: false, fixtureIcon: '🧱' },

      { row: 4, col: 0, zoneName: 'FISH MARKET', isOccupable: true },
      { row: 4, col: 1, zoneName: 'FISH MARKET', isOccupable: true },
      { row: 4, col: 2, zoneName: 'FISH MARKET', isOccupable: true, fixtureIcon: '🪑' },
      { row: 4, col: 3, zoneName: 'WAREHOUSE', isOccupable: true },
      { row: 4, col: 4, zoneName: 'WAREHOUSE', obstacleType: 'CRATE', isOccupable: false, fixtureIcon: '📦' },
    ],
    clues: [
      {
        id: 'clue-antonio-boat',
        text: 'Antonio estaba en un bote.',
        type: 'DIRECT',
        context: { suspectId: 'Antonio', expectedFixture: 'BOAT' },
        suspectId: 'Antonio',
        icon: '🚤',
        tag: 'Bote',
      },
      {
        id: 'clue-claire-east',
        text: 'Claire estaba en un bote y al este de Antonio.',
        type: 'CONDITIONAL',
        context: { primarySuspectId: 'Claire', referenceSuspectId: 'Antonio', relativeCols: 1 },
        suspectId: 'Claire',
        icon: '🧭',
        tag: 'Este',
      },
      {
        id: 'clue-delilah-fish',
        text: 'Delilah estaba en el Fish Market.',
        type: 'DIRECT',
        context: { suspectId: 'Delilah', expectedZone: 'FISH MARKET' },
        suspectId: 'Delilah',
        icon: '🐟',
        tag: 'Fish Market',
      },
    ],
  },
  {
    id: 'case-016-library-mystery',
    caseNumber: 16,
    title: 'The Library Mystery (Oficial)',
    difficulty: 'NORMAL',
    briefing: 'Caso oficial de Murdoku: Agatha fue asesinada en la biblioteca. El mapa muestra estanterías, sillones y plantas. Aplica las 4 reglas básicas: 1 por fila/columna, pistas obligatorias, el mapa como evidencia y encuentra quién quedó a solas («Alone with») con Agatha.',
    victimId: 'Agatha',
    murdererId: 'Charles',
    dimensions: { rows: 6, cols: 6 },
    suspects: [
      { id: 'Agatha', name: 'Agatha', initial: 'A', color: '#F8C8D2', attributes: { isVictim: true }, clueSummary: 'LA VÍCTIMA (Hallada en Library)', avatarIcon: '💀' },
      { id: 'Arthur', name: 'Arthur', initial: 'Ar', color: '#B8D0EB', attributes: {}, clueSummary: 'Al lado («Beside») de una planta', avatarIcon: '🧐' },
      { id: 'Beatrice', name: 'Beatrice', initial: 'B', color: '#E0AAFF', attributes: {}, clueSummary: 'Única persona («Only person») en la fila 6', avatarIcon: '👩🏻‍💼' },
      { id: 'Charles', name: 'Charles', initial: 'C', color: '#DDBEA9', attributes: {}, clueSummary: 'A solas con Agatha en Library (Asesino)', avatarIcon: '🕵🏻‍♂️' },
      { id: 'Diana', name: 'Diana', initial: 'D', color: '#FCD5CE', attributes: {}, clueSummary: 'Más al sur («South of») que Edward', avatarIcon: '👩🏼' },
      { id: 'Edward', name: 'Edward', initial: 'E', color: '#D8E2DC', attributes: {}, clueSummary: 'En Refreshments', avatarIcon: '👨🏻‍💻' },
    ],
    grid: [
      // Fila 0: LIBRARY
      { row: 0, col: 0, zoneName: 'LIBRARY', obstacleType: 'BOOKSHELF', isOccupable: false, fixtureIcon: '📚' },
      { row: 0, col: 1, zoneName: 'LIBRARY', isOccupable: true },
      { row: 0, col: 2, zoneName: 'LIBRARY', obstacleType: 'TABLE', isOccupable: false, fixtureIcon: '🪵' },
      { row: 0, col: 3, zoneName: 'LIBRARY', isOccupable: true }, // Charles [0, 3]
      { row: 0, col: 4, zoneName: 'LIBRARY', obstacleType: 'BOOKSHELF', isOccupable: false, fixtureIcon: '📚' },
      { row: 0, col: 5, zoneName: 'LIBRARY', isOccupable: true },

      // Fila 1: LIBRARY
      { row: 1, col: 0, zoneName: 'LIBRARY', isOccupable: true },
      { row: 1, col: 1, zoneName: 'LIBRARY', obstacleType: 'PLANT', isOccupable: false, fixtureIcon: '🪴' },
      { row: 1, col: 2, zoneName: 'LIBRARY', isOccupable: true }, // Agatha [1, 2]
      { row: 1, col: 3, zoneName: 'LIBRARY', isOccupable: true },
      { row: 1, col: 4, zoneName: 'LIBRARY', obstacleType: 'BOOKSHELF', isOccupable: false, fixtureIcon: '📚' },
      { row: 1, col: 5, zoneName: 'LIBRARY', isOccupable: true },

      // Fila 2: DISCUSSION CIRCLE (cols 0-2) / LIBRARY (cols 3-5)
      { row: 2, col: 0, zoneName: 'DISCUSSION CIRCLE', isOccupable: true },
      { row: 2, col: 1, zoneName: 'DISCUSSION CIRCLE', obstacleType: 'ARMCHAIR', isOccupable: true, fixtureIcon: '🛋️' },
      { row: 2, col: 2, zoneName: 'DISCUSSION CIRCLE', isOccupable: true },
      { row: 2, col: 3, zoneName: 'LIBRARY', isOccupable: true },
      { row: 2, col: 4, zoneName: 'LIBRARY', obstacleType: 'TABLE', isOccupable: false, fixtureIcon: '🪵' },
      { row: 2, col: 5, zoneName: 'LIBRARY', isOccupable: true },

      // Fila 3: DISCUSSION CIRCLE (cols 0-3) / REFRESHMENTS (cols 4-5)
      { row: 3, col: 0, zoneName: 'DISCUSSION CIRCLE', isOccupable: true }, // Arthur [3, 0]
      { row: 3, col: 1, zoneName: 'DISCUSSION CIRCLE', obstacleType: 'RUG', isOccupable: true, fixtureIcon: '🟪' },
      { row: 3, col: 2, zoneName: 'DISCUSSION CIRCLE', obstacleType: 'ARMCHAIR', isOccupable: true, fixtureIcon: '🛋️' },
      { row: 3, col: 3, zoneName: 'DISCUSSION CIRCLE', isOccupable: true },
      { row: 3, col: 4, zoneName: 'REFRESHMENTS', obstacleType: 'TABLE', isOccupable: false, fixtureIcon: '☕' },
      { row: 3, col: 5, zoneName: 'REFRESHMENTS', isOccupable: true }, // Edward [3, 5]

      // Fila 4: DISCUSSION CIRCLE (cols 0-3) / REFRESHMENTS (cols 4-5)
      { row: 4, col: 0, zoneName: 'DISCUSSION CIRCLE', obstacleType: 'PLANT', isOccupable: false, fixtureIcon: '🪴' },
      { row: 4, col: 1, zoneName: 'DISCUSSION CIRCLE', isOccupable: true },
      { row: 4, col: 2, zoneName: 'DISCUSSION CIRCLE', obstacleType: 'ARMCHAIR', isOccupable: true, fixtureIcon: '🛋️' },
      { row: 4, col: 3, zoneName: 'DISCUSSION CIRCLE', isOccupable: true },
      { row: 4, col: 4, zoneName: 'REFRESHMENTS', isOccupable: true },
      { row: 4, col: 5, zoneName: 'REFRESHMENTS', obstacleType: 'PLANT', isOccupable: false, fixtureIcon: '🪴' },

      // Fila 5: DISCUSSION CIRCLE (cols 0-3) / REFRESHMENTS (cols 4-5)
      { row: 5, col: 0, zoneName: 'DISCUSSION CIRCLE', isOccupable: true },
      { row: 5, col: 1, zoneName: 'DISCUSSION CIRCLE', obstacleType: 'ARMCHAIR', isOccupable: true, fixtureIcon: '🛋️' }, // Beatrice [5, 1]
      { row: 5, col: 2, zoneName: 'DISCUSSION CIRCLE', isOccupable: true },
      { row: 5, col: 3, zoneName: 'DISCUSSION CIRCLE', isOccupable: true },
      { row: 5, col: 4, zoneName: 'REFRESHMENTS', isOccupable: true }, // Diana [5, 4]
      { row: 5, col: 5, zoneName: 'REFRESHMENTS', obstacleType: 'TABLE', isOccupable: false, fixtureIcon: '🍹' },
    ],
    clues: [
      {
        id: 'clue-agatha-pos',
        text: 'Agatha (la víctima) fue encontrada en la Fila 2, Columna 3 de la Library.',
        type: 'DIRECT',
        context: { suspectId: 'Agatha', exactRow: 1, exactCol: 2, expectedZone: 'LIBRARY' },
        suspectId: 'Agatha',
        icon: '💀',
        tag: 'Víctima',
      },
      {
        id: 'clue-arthur-beside-plant',
        text: 'Arthur estaba al lado («Beside»: adyacente ortogonal) de la planta en el Discussion Circle.',
        type: 'EXCLUSION',
        context: { suspectId: 'Arthur', besideObstacleType: 'PLANT' },
        suspectId: 'Arthur',
        icon: '🪴',
        tag: 'Beside',
      },
      {
        id: 'clue-beatrice-row',
        text: 'Beatrice estaba sentada en la Fila 6 (Discussion Circle).',
        type: 'DIRECT',
        context: { suspectId: 'Beatrice', exactRow: 5, expectedZone: 'DISCUSSION CIRCLE' },
        suspectId: 'Beatrice',
        icon: '🛋️',
        tag: 'Sillón',
      },
      {
        id: 'clue-charles-alone-agatha',
        text: 'Charles quedó a solas («Alone with») con Agatha en la Library.',
        type: 'EXCLUSION',
        context: { suspectId: 'Charles', aloneWithSuspectId: 'Agatha' },
        suspectId: 'Charles',
        icon: '🔪',
        tag: 'Alone with',
      },
      {
        id: 'clue-edward-refreshments',
        text: 'Edward estaba en Refreshments.',
        type: 'DIRECT',
        context: { suspectId: 'Edward', expectedZone: 'REFRESHMENTS' },
        suspectId: 'Edward',
        icon: '☕',
        tag: 'Refreshments',
      },
      {
        id: 'clue-diana-south-edward',
        text: 'Diana estaba más abajo en el mapa («South of») que Edward.',
        type: 'CONDITIONAL',
        context: { primarySuspectId: 'Diana', referenceSuspectId: 'Edward', isSouthOf: true },
        suspectId: 'Diana',
        icon: '🧭',
        tag: 'South of',
      },
    ],
  },
];
